service: codepipeline-notifier

frameworkVersion: ">=1.44.1 <2.0.0"

custom:
  bucket: alis-codepipeline-notifier-${env:STAGE}
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.7
  stage: ${env:STAGE}
  region: ap-northeast-1
  environment:
    SLACK_NOTIFICATION_URL: ${env:SLACK_NOTIFICATION_URL}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL}

package:
  individually: true
  exclude:
    - .git/**
    - venv/**
    - tmp.*
    - .envrc*
    - deploy.sh
    - .python-version
    - .git*
    - package.json
    - README.md

functions:
  CodepipelineToSlack:
    handler: handlers/codepipeline_to_slack.lambda_handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.codepipeline"
            detail-type:
              - "CodePipeline Pipeline Execution State Change"
            detail:
              state:
                - CANCELED
                - FAILED
                - SUCCEEDED
